# Generated by Django 5.0.7 on 2024-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file_1080p',
            field=models.FileField(default='videos/default.mp4', upload_to='videos'),
        ),
    ]
